---
- name: Check fastfetch
  stat:
    path: /usr/bin/fastfetch
  register: fastfetch

- name: "Installing latest fastfetch"
  unarchive:
    src: "https://dl.fastfetch.org/fastfetch-1.2.6-linux-gnu-x86_64.tar.gz"
    dest: /usr/bin
    remote_src: yes
    mode: '0755'
    owner: root
    group: root
  become: true
  when: not (fastfetch.stat.exists)

- name: Copy fastfetch config to /etc/skel and users profile
  ansible.builtin.copy:
    src: "files/fastfetch"
    dest: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: '0644'
    directory_mode: '0755'
    force: true
  loop:
    - { path: "{{ user.home }}/.config", owner: "{{ user.name }}", group: "{{ user.name }}" }
    - { path: "/root/.config", owner: "root", group: "root" }
    - { path: "/etc/skel/.config", owner: "root", group: "root" }
  become: true
