---
# tasks file for oh_my_zsh
- name: Install Git
  ansible.builtin.package:
    state: present
    name: git
  become: true

- name: Install fish
  become: true
  ansible.builtin.package:
    name: fish
    state: present

- name: make the fisherman directory
  file:
    path="{{ user.home }}/.config/fish/functions"
    state=directory
    owner="{{ user.name }}"
    mode=0755
    recurse=yes

- name: install fisherman
  become: yes
  become_user: "{{ user.name }}"
  get_url:
    url="{{ item.url }}"
    dest="{{ item.dest }}"
  with_items:
    - {url: "https://git.io/fisherman", dest: "{{ user.home }}/.config/fish/functions/fisher.fish"}

- name: install bass
  become: yes
  become_user: "{{ user.name }}"
  command: /usr/bin/fish -c 'fisher eds/bass paths'

- name: change the shell to fish
  user:
    name="{{ user.name }}"
    shell=/usr/bin/fish

- name: install zoxide
  ansible.builtin.shell:
    fisher install kidonng/zoxide.fish

- name: Tasks for starship
  ansible.builtin.include_tasks: starship.yml

- name: install pfetch
  ansible.builtin.include_tasks: pfetch.yml
