- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False

  tasks:
    - include_tasks: tasks/users.yml
    - include_tasks: tasks/cron.yml
    - include_tasks: tasks/packages.yml
    # - include_tasks: tasks/neovim.yml
  
  roles:
     - neovim
  vars:
    neovim_user_id: abayoumy

    neovim_configuration: |
      set number
      set tabstop=4
      set shiftwidth=4

    # neovim_plugins:
    #   - HerringtonDarkholme/yats.vim
    #   - name: mhartington/nvim-typescript
    #     options:
    #       do: ./install.sh
