- hosts: localhost
  connection: local
  become: true
  vars:
    cmdr_bin_dir : /usr/local/bin
    user : abayoumy
  pre_tasks:
  - name: Copy dotfiles
    ansible.builtin.copy:
      src: files/dnf.conf
      dest: /etc/dnf/dnf.conf
      owner: root
      group: root
      mode: '0644'
    run_once: true
    when: ansible_facts['os_family'] == "RedHat"
  #   - name: update apt repositories
  #     apt:
  #       update_cache: yes
  #     changed_when: False
  #     when: ansible_facts['os_family'] == "Debian"

  #   - name: update dnf repositories
  #     dnf:
  #       update_cache: yes
  #     changed_when: False
  #     when: ansible_facts['os_family'] == "RedHat"
  tasks:
    - include_tasks: tasks/users.yml
    - include_tasks: tasks/update.yml
    - include_tasks: tasks/packages.yml
    - include_tasks: tasks/neovim.yml
    - include_tasks: tasks/pfetch.yml
    - include_tasks: tasks/zellij.yml
    - include_tasks: tasks/cron.yml
