- hosts: localhost
  connection: local
  gather_facts: yes
  become: true
  pre_tasks:
    - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_facts['os_family'] == "Debian"
    - name: Update all packages to their latest version
      ansible.builtin.apt:
        name: "*"
        state: latest
      when: ansible_facts['os_family'] == "Debian"
      
    - name: dnf conf
      ansible.builtin.lineinfile:
        path: /etc/dnf/dnf.conf
        line: "{{ item }}"
      loop:
        - max_parallel_downloads=20
        - fastestmirror=true
        - deltarpm=true
      run_once: true
      when: ansible_facts['os_family'] == "RedHat"
    - name: Upgrade all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
      when: ansible_facts['os_family'] == "RedHat"
    
    - name: Autoremove unneeded packages installed as dependencies
      ansible.builtin.dnf:
        autoremove: yes
      when: ansible_facts['os_family'] == "RedHat"
    
  tasks:
    # - include_tasks: tasks/info.yml
    # - include_tasks: tasks/users.yml
    # - include_tasks: tasks/packages.yml
    # - include_tasks: tasks/neovim.yml
    # - include_tasks: tasks/pfetch.yml
    # - include_tasks: tasks/cron.yml
    - name: Set roles
      ansible.builtin.set_fact:
        run_roles: "{{ ansible_run_tags != ['all'] and ansible_run_tags or default_roles | difference(exclude_roles | default([])) }}"
      tags:
        - always

    - name: Display roles
      ansible.builtin.debug:
        var: run_roles
      tags:
        - always

    - name: Run roles
      ansible.builtin.include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ run_roles }}"
      tags:
        - always