- name: Linux Bootstrap
  hosts: localhost
  connection: local
  gather_facts: true
  become: true
  pre_tasks:
    - name: Detect Host User
      ansible.builtin.import_tasks: pre_tasks/whoami.yml
      tags:
        - always

    - name: Install ansible reqirements
      ansible.builtin.import_tasks: pre_tasks/install_requirements.yml
      tags:
        - always

    - name: Create users
      ansible.builtin.import_tasks: pre_tasks/users.yml
      tags:
        - always
      when: host_user == "root"

    - name: Update
      ansible.builtin.import_tasks: pre_tasks/update.yml
      tags:
        - always

    # - name: Security tower_settings
    #   ansible.builtin.import_tasks: pre_tasks/security.yml
    #   tags:
    #     - always

  tasks:
    - name: Set roles
      ansible.builtin.set_fact:
        run_roles: "{{ ansible_run_tags != ['all'] and ansible_run_tags or default_roles | difference(exclude_roles | default([])) }}"
      tags:
        - always
      when: host_user != "root"

    - name: Set roles for root
      ansible.builtin.set_fact:
        run_roles: "{{ ansible_run_tags != ['all'] and ansible_run_tags or root_roles | difference(exclude_roles | default([])) }}"
      tags:
        - always
      when: host_user == "root"

    - name: Display roles
      ansible.builtin.debug:
        var: run_roles
      tags:
        - always

    - name: Run roles
      ansible.builtin.include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ run_roles }}"
      tags:
        - always
