# alias ls='ls -CHG --color'
# alias la='ls -ahG'
# alias ll='ls -ahlG'
ld='eza -lD'
lf='eza -lf --color=always | grep -v /'
lh='eza -dl .* --group-directories-first'
ll='eza -al --group-directories-first'
ls='eza -alf --color=always --sort=size | grep -v /'
lt='eza -al --sort=modified'
alias du='du -sh * | sort -h'
alias vi='nvim'
alias vim='nvim'