- uri:                                                               
    url: https://api.github.com/repos/Macchina-CLI/macchina/releases/latest
    return_content: true                                             
  register: json_reponse                                             

- name: install neovim macchina
  unarchive:
    src: "{{ json_reponse.json.tarball_url }}"
    dest: /tmp/
    remote_src: yes
    mode: a+x
    # owner: root
    # group: root
    extra_opts: [--strip-components=1]




