- name: install neovim 64
  unarchive:
    src: https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.tar.gz
    dest: /usr/local
    remote_src: yes
    mode: 0755
    owner: root
    group: root
    extra_opts: [--strip-components=1]
  # when: ansible_architecture == "x86_64"

- name: Clone a NvChad repository
  git:
    repo: https://github.com/NvChad/NvChad
    dest: /home/abayoumy/.config/nvim
    clone: yes
    update: yes
    depth: 1
- name: change perms
  file:
  dest: /home/abayoumy/.config/nvim
  state: directory
  mode: 0755
  owner: abayoumy