- name: install neovim 64
  unarchive:
    src: https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.tar.gz
    dest: /usr/local
    remote_src: yes
    mode: 0755
    owner: root
    group: root
    extra_opts: [--strip-components=1]
  # when: ansible_architecture == "x86_64"
