- name: Install packages
  apt:
    name:
      - bpytop
      - mc
      - fish
      - git
      - byobu
      - software-properties-common
      - rsync
      - fuse3
      - xdg-user-dirs
      - byobu


- name: Enable SSH
  ansible.builtin.systemd:
    state: restarted
    enabled: true
    name: sshd