# - name: Add neovim ppa
#   ansible.builtin.apt_repository:
#     repo: ppa:neovim-ppa/stable

- name: Install packages
  apt:
    name:
      - bpytop
      - mc
      - fish
      - git
      - byobu
      - software-properties-common
      - rsync
      - fuse3
      - xdg-user-dirs

- name: Enable SSH
  ansible.builtin.systemd:
    state: restarted
    enabled: true
    name: sshd