- name: Install packages
  apt:
    name:
      - git
      - software-properties-common
      - fuse3
      - xdg-user-dirs
      - unzip
      - bash-completion
      - wget
      - wmctrl
      - eza
      - fish
      - btop
      - byobu
    state: present
  when: ansible_facts['os_family'] == "Debian"
  run_once: false
  
- name: Install packages
  dnf:
    name:
      - '@Development Tools'
      - epel-release
    state: latest
  when: ansible_facts['os_family'] == "RedHat"
  run_once: true
- name: Install packages
  dnf:
    name:
      - git
      - fuse3
      - xdg-user-dirs
      - unzip
      - bash-completion
      - wget
      - wmctrl
      - eza
      - openssh-server
      - fish
      - btop
      - byobu
    state: present
  when: ansible_facts['os_family'] == "RedHat"
  run_once: false

- name: Install packages
  pacman:
    name:
      - git
      - fuse3
      - xdg-user-dirs
      - unzip
      - bash-completion
      - wget
      - wmctrl
      - eza
      - openssh
      - fish
      - btop
      - byobu
    state: latest
    update_cache: true
  when: ansible_facts['os_family'] == "Archlinux"
  run_once: false

- name: Enable SSH
  ansible.builtin.systemd:
    state: restarted
    enabled: true
    name: sshd
  run_once: true
