# - name: Add neovim ppa
#   ansible.builtin.apt_repository:
#     repo: ppa:neovim-ppa/stable

- name: Install packages
  apt:
    name:
      - bpytop
      - mc
      - fish
      - git
      - tmux
      - software-properties-common
      - rsync