- name: Install packages
  apt:
    name:
      - bpytop
      - mc
      - git
      - tmux
      - software-properties-common
      - rsync
      - fuse3
      - xdg-user-dirs
      - unzip
      - python3-neovim
      - bash-completion
      - aria2
      - wget
    state: latest
  when: ansible_facts['os_family'] == "Debian"

- name: Install packages
  dnf:
    name:
      - '@development-tools'
      - epel-release
      - mc
      - git
      - tmux
      - rsync
      - fuse3
      - xdg-user-dirs
      - unzip
      - python3-neovim
      - bash-completion
      - aria2
      - wget
    state: latest
  when: ansible_facts['os_family'] == "RedHat"

- name: Enable SSH
  ansible.builtin.systemd:
    state: restarted
    enabled: true
    name: sshd

