- name: Install packages
  apt:
    name:
      - git
      - tmux
      - software-properties-common
      - fuse3
      - xdg-user-dirs
      - unzip
      - bash-completion
      - wget
      - wmctrl
    state: latest
  when: ansible_facts['os_family'] == "Debian"

- name: Install packages
  dnf:
    name:
      - '@Development Tools'
      - epel-release
      - git
      - tmux
      - fuse3
      - xdg-user-dirs
      - unzip
      - bash-completion
      - wget
      - wmctrl
    state: latest
  when: ansible_facts['os_family'] == "RedHat"

- name: Enable SSH
  ansible.builtin.systemd:
    state: restarted
    enabled: true
    name: sshd

