- name: Install packages
  apt:
    name:
      - git
      - tmux
      - software-properties-common
      - fuse3
      - xdg-user-dirs
      - unzip
      - bash-completion
      - wget
      - wmctrl
    state: latest
  when: ansible_facts['os_family'] == "Debian"
  run_once: true
  
- name: Install packages
  dnf:
    name:
      - '@Development Tools'
      - epel-release
    state: latest
  when: ansible_facts['os_family'] == "RedHat"
  run_once: true
- name: Install packages
  dnf:
    name:
      - git
      - tmux
      - fuse3
      - xdg-user-dirs
      - unzip
      - bash-completion
      - wget
      - wmctrl
      - eza
    state: latest
  when: ansible_facts['os_family'] == "RedHat"
  run_once: false
- name: Enable SSH
  ansible.builtin.systemd:
    state: restarted
    enabled: true
    name: sshd
  run_once: true
