- name: check nvim exist
  stat:
    path: /usr/local/bin/pfetch
  register: pfetch

- name: install neovim 64
  get_url:
    url: https://raw.githubusercontent.com/dylanaraps/pfetch/master/pfetch
    dest: /usr/local/bin/pfetch
    mode: 0766
  when: not (pfetch.stat.exists) 

