- name: check pfetch
  stat:
    path: /usr/local/bin/pfetch
  register: pfetch

- name: install pfetch
  get_url:
    url: https://raw.githubusercontent.com/dylanaraps/pfetch/master/pfetch
    dest: /usr/local/bin/pfetch
    mode: a+x
  when: not (pfetch.stat.exists) 

