- name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_facts['os_family'] == "Debian"
  
- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
  when: ansible_facts['os_family'] == "Debian"
- name: Upgrade all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
  when: ansible_facts['os_family'] == "RedHat"

- name: Autoremove unneeded packages installed as dependencies
  ansible.builtin.dnf:
    autoremove: yes

- name: Upgrade all packages
  community.general.pacman:
    update_cache: true
    upgrade: true
  when: ansible_facts['os_family'] == "Archlinux"