- name: copy sudoers_abayoumy
  copy:
    src: files/sudoers_abayoumy
    dest: /etc/sudoers.d/abayoumy
    owner: root
    group: root
    mode: 0440

- name: Set authorized key taken from file
  ansible.posix.authorized_key:
    user: abayoumy
    state: present
    key: "{{ lookup('file', 'files/id_ed25519.pub') }}"