- name: Create Users Task
  user:
    name: "{{ item }}"
    state: present
    password: ""
    shell: /bin/fish
    group: "{{ item }}"
  loop:
    - abayoumy

- name: copy sudoers_abayoumy
  copy:
    src: files/sudoers_abayoumy
    dest: /etc/sudoers.d/abayoumy
    owner: root
    group: root
    mode: 0440

- name: Import all files/*.pub authorized key
  ansible.posix.authorized_key:
    user: abayoumy
    state: present
    key: "{{ lookup('file', '{{ item }}') }}"
  with_fileglob:
    - "files/*.pub"