- name: Create Users Task
  user:
    name: "{{ item }}"
    state: present
    password: ""
    shell: /bin/bash
    append: true
    groups: users
  loop:
    - {{ user }}

# - name: copy sudoers_abayoumy
#   copy:
#     src: files/sudoers_abayoumy
#     dest: /etc/sudoers.d/abayoumy
#     owner: root
#     group: root
#     mode: 0440
#     force: no

- name: Allow  user to run any commands without password
  community.general.sudoers:
    name: user-do-as-root
    state: present
    user: {{ user }}
    runas: root
    commands: ALL
    nopassword: true

- name: Import all files/*.pub authorized key
  ansible.posix.authorized_key:
    user: {{ user }}
    state: present
    key: "{{ lookup('file', '{{ item }}') }}"
  with_fileglob:
    - "files/*.pub"

- name: Copy dotfiles
  ansible.builtin.copy:
    src: files/dotfiles/
    dest: /home/{{ user }}/
    owner: {{ user }}
    group: {{ user }}
    mode: '0755'
    force: no

- name: Copy Bash files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /home/{{ user }}/
    owner: {{ user }}
    group: {{ user }}
    mode: '0755'
    force: yes
  with_fileglob:
    - "files/dotfiles/.bash*"

- name: Copy Bash files to root
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /root/
    owner: root
    group: root
    mode: '0755'
    force: yes
  with_fileglob:
    - "files/dotfiles/.bash*"
