- name: Create Users Task
  user:
    name: "{{ item }}"
    state: present
    password: "{{ ambkan | password_hash('sha512','A512') }}"
    shell: /bin/bash
    group: "{{ admin_group }}"
  loop:
    - abayoumy

- name: copy sudoers_abayoumy
  copy:
    src: files/sudoers_abayoumy
    dest: /etc/sudoers.d/abayoumy
    owner: root
    group: root
    mode: 0440

- name: Import all files/*.pub authorized key
  ansible.posix.authorized_key:
    user: abayoumy
    state: present
    key: "{{ lookup('file', '{{ item }}') }}"
  with_fileglob:
    - "files/*.pub"