- name: Install ansible.posix collection
  command: ansible-galaxy collection install ansible.posix
  register: install_posix
  changed_when: '"Nothing to do." not in install_posix.stdout'


- name: Create Users Task
  user:
    name: "{{ item }}"
    state: present
    password: ""
    shell: /bin/bash
    append: true
    groups: users
  loop:
    - abayoumy

- name: copy sudoers_abayoumy
  copy:
    src: files/sudoers_abayoumy
    dest: /etc/sudoers.d/abayoumy
    owner: root
    group: root
    mode: 0440
    force: no

- name: Import all files/*.pub authorized key
  ansible.posix.authorized_key:
    user: abayoumy
    state: present
    key: "{{ lookup('file', '{{ item }}') }}"
  with_fileglob:
    - "files/*.pub"

- name: Copy dotfiles
  ansible.builtin.copy:
    src: files/dotfiles/
    dest: /home/abayoumy/
    owner: abayoumy
    group: abayoumy
    mode: '0755'
    force: no

