---
- name: "SSH | Ensure .ssh folder exists"
  ansible.builtin.file:
    path: "{{ user.home }}/.ssh"

- name: "Check if SSH Key exists"
  ansible.builtin.stat:
    path: "{{ user.home }}/.ssh/id_ed25519"
  register: sshkey

- name: "Create SSH Key for {{ user.name }}"
  community.crypto.openssh_keypair:
    path: "{{ user.home }}/.ssh/id_ed25519"
    size: 2048
    type: ed25519
    state: present
    force: true
  when: not (sshkey.stat.exists)

- name: "SSH | Copy SSH keys"
  ansible.builtin.copy:
    dest: "{{ user.home }}/.ssh/{{ ssh_key_item.key }}"
    content: "{{ ssh_key_item.value }}"
    mode: "0600"
  no_log: true
  loop_control:
    loop_var: ssh_key_item
  with_items: "{{ ssh_key | default({}) | dict2items }}"

- name: Copy config
  ansible.builtin.copy:
    dest: "{{ user.home }}/.ssh/config"
    src: "config"
    mode: '600'
    owner: "{{ user.name }}"
    group: "{{ user.name }}"

- name: Add  ssh keys for abayoumy
  ansible.posix.authorized_key:
    user: "{{ user.name }}"
    state: present
    key: "{{ lookup('file', '{{ item }}') }}"
  with_fileglob:
    - "files/*.pub"
  become: true

- name: Add ssh keys for ansible
  ansible.posix.authorized_key:
    user: ansible
    state: present
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKG7DNrs2hcOmEG4gXRVyvAgrvoiE2iIBSFoPtRYPHl9 ansible"
  become: true

- name: Secure SSH
  ansible.builtin.import_tasks: roles.ssh.tasks.secure_ssh.yml
  become: true
