---
- name: "SSH | Copy SSH keys"
  copy:
    dest: "{{ ansible_user_dir }}/.ssh/{{ ssh_key_item.key }}"
    content: "{{ ssh_key_item.value }}"
    mode: "0600"
  no_log: true
  loop_control:
    loop_var: ssh_key_item
  with_items: "{{ ssh_key | default({}) | dict2items }}"

- name: Copy config
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.ssh/config"
    src: "config"

  - name: add  ssh keys
    authorized_key:
      user: abayoumy
      key: "{{ lookup('pipe','cat *.pub') }}"
      state: present
      
  - name: add  ssh keys
    authorized_key:
      user: ansible
      state: present
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKG7DNrs2hcOmEG4gXRVyvAgrvoiE2iIBSFoPtRYPHl9 ansible"
