---
- name: "SSH | Ensure .ssh folder exists"
  file:
    path: "{{ user.home }}/.ssh"

- name: "Create SSH Key for {{ user.name }}"
  community.crypto.openssh_keypair:
    path: "{{ user.home }}/.ssh/id_ed25519"
    size: 2048
    type: ed25519
    state: present
    force: no

- name: "SSH | Copy SSH keys"
  copy:
    dest: "{{ user.home }}/.ssh/{{ ssh_key_item.key }}"
    content: "{{ ssh_key_item.value }}"
    mode: "0600"
  no_log: true
  loop_control:
    loop_var: ssh_key_item
  with_items: "{{ ssh_key | default({}) | dict2items }}"

- name: Copy config
  ansible.builtin.copy:
    dest: "{{ user.home }}/.ssh/config"
    src: "config"

- name: add  ssh keys for abayoumy
  authorized_key:
    user: "{{ user.name }}"
    state: present
    key: "{{ lookup('file', '{{ item }}') }}"
  with_fileglob:
    - "files/*.pub"
  become: true
    
- name: add ssh keys for ansible
  authorized_key:
    user: ansible
    state: present
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKG7DNrs2hcOmEG4gXRVyvAgrvoiE2iIBSFoPtRYPHl9 ansible"
  become: true
  