---
- name: "System | {{ ansible_distribution }} | Update pacman"
  community.general.pacman:
    update_cache: true
    upgrade: true
    state: latest
  become: true

- name: "System | {{ ansible_distribution }} | Install"
  community.general.pacman:
    name:
      - jq
      - open-iscsi
      - git
      - fuse3
      - xdg-user-dirs
      - unzip
      - wget
      - wmctrl
      - eza
      - openssh
      - btop
      - bat
      - byobu
      - dust
      - ripgrep
      - fd
    state: present
  become: true

- name: Check yay
  stat:
    path: /usr/bin/yay
  register: yay

- name: Check paru
  stat:
    path: /usr/bin/paru
  register: paru

- name: "System | {{ ansible_distribution }} | Install yay"
  when: 
    - not yay.stat.exists
    - not host_user == 'root' 
  block:
  - name: Clone yay
    git:
      repo: https://aur.archlinux.org/yay-bin.git
      dest: "/tmp/yay"
      update: true
  - name: Build and install yay
    ansible.builtin.command:
      chdir: "/tmp/yay"
      cmd: "makepkg -sfi --noconfirm"
      creates: /usr/bin/yay
    become: false
- name: "System | {{ ansible_distribution }} | Install paru"
  when: 
    - not paru.stat.exists
    - not host_user == 'root
  block:
  - name: Clone paru
    git:
      repo: https://aur.archlinux.org/paru-bin.git
      dest: "/tmp/paru"
      update: true
  - name: Build and install paru
    ansible.builtin.command:
      chdir: "/tmp/paru"
      cmd: "makepkg -sfi --noconfirm"
      creates: /usr/bin/paru
    become: false
