---

# In Ubuntu we have to install it from another repository
# so it's better to check if it's already installed
- name: Check if eza is already installed on Ubuntu
  ansible.builtin.shell: >
    eza --version
  register: eza_rc
  failed_when: false

- name: Repository for eza on Ubuntu
  become: true
  ansible.builtin.shell: |
    mkdir -p /etc/apt/keyrings
    wget -qO- https://raw.githubusercontent.com/eza-community/eza/main/deb.asc | gpg --dearmor -o /etc/apt/keyrings/gierens.gpg
    echo "deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main" | tee /etc/apt/sources.list.d/gierens.list
    chmod 644 /etc/apt/keyrings/gierens.gpg /etc/apt/sources.list.d/gierens.list
    apt update
  when: eza_rc.rc != 0

- name: "System | {{ ansible_distribution }} | Update APT Repos and Upgrade APT Packages"
  ansible.builtin.apt:
    update_cache: true
    upgrade: full
    autoremove: true
    autoclean: true
  become: true

- name: "System | {{ ansible_distribution }} | Install"
  ansible.builtin.apt:
    name:
      - jq
      - open-iscsi
      - git
      - fuse3
      - eza
      - xdg-user-dirs
      - unzip
      - wget
      - wmctrl
      - openssh-server
      - btop
      - bat
      - byobu
      - gpg
      - ripgrep
      - fd-find
    state: present
  become: true

- name: Check if zoxide is already installed on Ubuntu Focal
  ansible.builtin.shell: >
    zoxide --version
  register: zoxide_rc
  failed_when: false
  changed_when: false
  when: ansible_os_family == 'Debian' and ansible_distribution_version is version('20.10', '<')

- name: Get latest zoxide version
  ansible.builtin.uri:
    url: "https://api.github.com/repos/ajeetdsouza/zoxide/releases/latest"
    return_content: true
  register: zoxide_release

- name: Install zoxide 
  become: true
  ansible.builtin.unarchive:
    src: "{{ zoxide_release.json.assets[0].url }}"
    dest: /usr/local/bin
    remote_src: true
  when: zoxide_rc.rc != 0

- name: Check if procs is already installed
  ansible.builtin.shell: >
    procs --version
  register: procs_rc
  failed_when: false

- name: Get latest procs version
  ansible.builtin.uri:
    url: "https://api.github.com/repos/dalance/procs/releases/latest"
    return_content: true
  register: procs_release
  when: procs_rc.rc != 0

- name: Install latest procs
  become: true
  ansible.builtin.unarchive:
    src: "{{ procs_release.json.assets[0].url }}"
    dest: /usr/local/bin
    remote_src: true
  when: procs_rc.rc != 0
