---
- name: "System | Checking for Distribution Config: {{ ansible_os_family }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_os_family }}.yml"
  register: system_distribution_config

- name: "System | Run Tasks: {{ ansible_os_family }}"
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"
  when: system_distribution_config.stat.exists

- name: "System | Set hosts"
  ansible.builtin.template:
    dest: "/etc/hosts"
    src: hosts.j2
    mode: "0644"
  become: true
  when: not ansible_host_environment_is_wsl

- name: Get current timezone
  ansible.builtin.command: timedatectl show --property=Timezone --value
  register: current_timezone
  changed_when: false

- name: Set timezone to Africa/Cairo
  community.general.timezone:
    name: Africa/Cairo
  become: yes
  become_method: sudo
  when: current_timezone.stdout != 'Africa/Cairo'




- name: System | Detecting win32yank
  ansible.builtin.stat:
    path: /usr/local/bin/win32yank.exe
  register: win32yank_installed
  when: ansible_host_environment_is_wsl

- name: "System | Install win32yank.exe"
  when:
    - ansible_host_environment_is_wsl
    - not win32yank_installed.stat.exists
  block:
    - name: Download win32yank zip
      ansible.builtin.get_url:
        url: https://github.com/equalsraf/win32yank/releases/download/v0.0.4/win32yank-x64.zip
        dest: /tmp/win32yank.zip
        mode: "0755"

    - name: System | Unzip win32yank.exe
      ansible.builtin.unarchive:
        src: /tmp/win32yank.zip
        dest: /tmp
        mode: "0755"

    - name: System | Copy win32yank into path
      ansible.builtin.copy:
        remote_src: true
        src: /tmp/win32yank.exe
        dest: /usr/local/bin/win32yank.exe
        mode: "0755"
      become: true

    - name: System | Remove tmp files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/win32yank.zip
        - /tmp/win32yank.exe

- name: Check if IPv6 is enabled
  ansible.builtin.command: sysctl -n net.ipv6.conf.all.disable_ipv6
  register: ipv6_status
  changed_when: false
  check_mode: no

- name: Disable IPv6
  block:
    - name: Disable IPv6 via sysctl
      ansible.builtin.sysctl:
        name: "{{ item }}"
        value: '1'
        state: present
        reload: yes
      loop:
        - net.ipv6.conf.all.disable_ipv6
        - net.ipv6.conf.default.disable_ipv6
        - net.ipv6.conf.lo.disable_ipv6
      become: yes

    - name: Check if GRUB is installed
      ansible.builtin.stat:
        path: /etc/default/grub
      register: grub_installed

    - name: Update GRUB to disable IPv6
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="ipv6.disable=1"'
      become: yes
      notify: Update GRUB
      when: grub_installed.stat.exists
  
  when: ipv6_status.stdout == "0"
