- name: "System | {{ ansible_distribution }} | Upgrade all packages"
  ansible.builtin.dnf:
    name: "*"
    state: latest
  become: true
- name: "System | {{ ansible_distribution }} | Install 1/2"
  dnf:
    name:
      - '@Development Tools'
      - epel-release
    state: latest
  become: true
- name: "System | {{ ansible_distribution }} | Install 2/2"
  dnf:
    name:
      - git
      - fuse3
      - eza
      - xdg-user-dirs
      - unzip
      - wget
      - wmctrl
      - openssh-server
      - btop
      - util-linux-user
      - byobu
      - bat
      - ripgrep
      - fd-find
    state: latest
  become: true

- name: Enable ssh service
  ansible.builtin.systemd_service:
    name: sshd
    enabled: true
  become: true

- name: Make sure sshd service unit is running
  ansible.builtin.systemd_service:
    state: started
    name: sshd