---
- name: check pfetch
  stat:
    path: /usr/local/bin/pfetch
  register: pfetch

- name: check pfetch link
  stat:
    path: /usr/bin/pfetch
  register: pfetch_link

- name: Get latest pfetch-rs release info
  uri:
    url: https://api.github.com/repos/Gobidev/pfetch-rs/releases/latest
    return_content: yes
  register: pfetch_release_info

- name: "Installing latest pfetch-rs"
  unarchive:
    src: "{{ pfetch_release_info.json.assets | selectattr('name', 'match', 'pfetch-linux-gnu-x86_64.tar.gz') | map(attribute='browser_download_url') | first }}"
    dest: /usr/local/bin
    remote_src: yes
    mode: '0755'
    owner: root
    group: root
  become: true
  when: not (pfetch.stat.exists)

- name: Create a symbolic link
  ansible.builtin.file:
    src: /usr/local/bin/pfetch
    dest: /usr/bin/pfetch
    owner: root
    group: root
    state: link
  become: true
  when: not (pfetch_link.stat.exists) 

# https://api.github.com/repos/Gobidev/pfetch-rs/releases/latest

# html_url	"https://github.com/Gobidev/pfetch-rs/releases/tag/v2.11.0"
