---
- name: "Tmux | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: tmux_distribution_config

- name: "Tmux | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: tmux_distribution_config.stat.exists

- name: "Tmux | Install TPM"
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ user.home }}/.tmux/plugins/tpm"

- name: change ownership
  file:
    path: "{{ user.home }}/.tmux/"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    state: directory
    recurse: yes
  become: true

- name: "Tmux | Configure tmux"
  ansible.builtin.copy:
    src: .tmux.conf
    dest: "{{ user.home }}"
    mode: "0644"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    directory_mode: "0755"
    force: true
