- name: Check fastfetch
   ansible.builtin.stat:
    path: /usr/bin/fastfetch
  register: fastfetch

- name: Get latest fastfetch release info
  uri:
    url: https://api.github.com/repos/fastfetch-cli/fastfetch/releases/latest
    return_content: yes
  register: fastfetch_release_info

- name: Get installed fastfetch version
  command: /usr/bin/fastfetch --version
  register: installed_fastfetch_version
  changed_when: false
  failed_when: false
  when: fastfetch.stat.exists

- name: Remove old fastfetch version
  file:
    path: /usr/bin/fastfetch
    state: absent
  become: true
  when: 
    - fastfetch.stat.exists
    - installed_fastfetch_version.stdout is defined
    - installed_fastfetch_version.stdout.split()[1] != fastfetch_release_info.json.tag_name[1:]

- name: "Installing latest fastfetch"
  get_url:
    url: "{{ fastfetch_release_info.json.assets | selectattr('name', 'match', 'fastfetch-linux-amd64.tar.gz') | map(attribute='browser_download_url') | first }}"
    dest: /tmp/fastfetch.tar.gz
  delegate_to: localhost

- name: "Extract fastfetch (using shell module)"
  shell: "tar -xzf /tmp/fastfetch.tar.gz -C /tmp" 
  delegate_to: localhost
  become: true

- name: "Copy fastfetch to /usr/bin"
  ansible.builtin.copy:
    src: /tmp/fastfetch-linux-amd64/usr/bin/fastfetch
    dest: /usr/bin/fastfetch
    mode: 0755
    owner: root
    group: root
  become: true

- name: "Remove fastfetch archive and temporary directory"
  file:
    path: /tmp/fastfetch.tar.gz
    state: absent
  delegate_to: localhost

- name: "Remove fastfetch extraction directory"
  file:
    path: /tmp/fastfetch-linux-amd64
    state: absent
  delegate_to: localhost

- name: ensures fastfetch dir exists
  file: 
    path: "{{ item.path }}"
    state: directory
  loop:
    - { path: "{{ user.home }}/.config/fastfetch" }
    - { path: "/root/.config/fastfetch" }
    - { path: "/etc/skel/.config/fastfetch" }
  become: true

- name: Copy fastfetch config to /etc/skel and users profile
  ansible.builtin.copy:
    src: "files/config.jsonc"
    dest: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: '0644'
    directory_mode: '0755'
    force: true
  loop:
    - { path: "{{ user.home }}/.config/fastfetch", owner: "{{ user.name }}", group: "{{ user.name }}" }
    - { path: "/root/.config/fastfetch", owner: "root", group: "root" }
    - { path: "/etc/skel/.config/fastfetch", owner: "root", group: "root" }
  become: true
