- name: check nvim exist
   ansible.builtin.stat:
    path: /usr/local/bin/nvim
  register: nvim

- name: install neovim 64
  unarchive:
    src: https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.tar.gz
    dest: /usr/local
    remote_src: yes
    mode: '0755'
    owner: root
    group: root
    extra_opts: [--strip-components=1]
  when: not (nvim.stat.exists) and ansible_architecture == "x86_64"  
  run_once: true
# - name: Creates config directory
#   file:
#     path: ~/.config/nvim
#     state: directory
#   run_once: true
- name: Copy dotfiles
  ansible.builtin.copy:
    src: files/dotfiles/.config/nvim
    dest: /home/abayoumy/.config
    owner: abayoumy
    group: abayoumy
    mode: '0755'
  run_once: true
