- name: check pfetch
  stat:
    path: /usr/local/bin/pfetch
  register: pfetch

- name: check pfetch link
  stat:
    path: /usr/local/bin/pfetch
  register: pfetch_link

- name: install pfetch
  get_url:
    url: https://raw.githubusercontent.com/dylanaraps/pfetch/master/pfetch
    dest: /usr/local/bin/pfetch
    mode: a+x
  when: not (pfetch.stat.exists) 


- name: Create a symbolic link
  ansible.builtin.file:
    src: /usr/local/bin/pfetch
    dest: /usr/bin/pfetch
    owner: root
    group: root
    state: link
  when: not (pfetch_link.stat.exists) 
