- name: Set dnf conf
  ansible.builtin.lineinfile:
    path: /etc/dnf/dnf.conf
    line: "{{ item }}"
  loop:
    - max_parallel_downloads=20
    - fastestmirror=true
    - deltarpm=true
  run_once: true
  when: ansible_facts['os_family'] == "RedHat"

- name: Upgrade all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
  become: true
  when: ansible_facts['os_family'] == "RedHat"

- name: Autoremove unneeded packages installed as dependencies
  ansible.builtin.dnf:
    autoremove: yes
  become: true
  when: ansible_facts['os_family'] == "RedHat"
