- name: Create Users Task
  user:
    name: "{{ item }}"
    password: ""
    shell: /bin/bash
    append: true
    groups: users
    state: present
    update_password: on_create
  loop:
    - "{{ user }}"
    - ansible
  run_once: true
  become: true

- name: Allow  abayoumy to run any commands without password
  community.general.sudoers:
    name: abayoumy
    state: present
    user: abayoumy
    runas: root
    commands: ALL
    nopassword: true
  become: true

- name: Allow  ansible to run any commands without password
  community.general.sudoers:
    name: ansible
    state: present
    user: ansible
    runas: root
    commands: ALL
    nopassword: true
  become: true

- name: Copy Bash files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /home/"{{ user }}"/
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0755'
    force: yes
  with_fileglob:
    - "files/bash/.bash*"

