- name: Copy dotfiles to /etc/skel and root user profile
  ansible.builtin.copy:
    src: "files/dotfiles/"
    dest: "{{ item }}"
    owner: root
    group: root
    mode: '0644'
    directory_mode: '0755'
  loop:
    - "/etc/skel/"
    - "/root/"
  become: true

- name: Create Users
  user:
    name: "{{ item }}"
    password: ""
    shell: /bin/bash
    append: true
    groups: users
    state: present
    update_password: on_create
  loop:
    - "{{ user.name }}"
    - ansible
  run_once: true
  become: true

- name: "Add {{ user.name }} to sudoers"
  community.general.sudoers:
    name: "{{ user.name }}"
    state: present
    user: "{{ user.name }}"
    runas: root
    commands: ALL
    nopassword: true
  become: true

- name: Add ansible to sudoers
  community.general.sudoers:
    name: ansible
    state: present
    user: ansible
    runas: root
    commands: ALL
    nopassword: true
  become: true

- name: "Create SSH Key for {{ user.name }}"
  community.crypto.openssh_keypair:
    path: "{{ user.home }}/.ssh/id_ed25519"
    size: 2048
    type: ed25519
    state: present
    force: no
    
- name: "add  ssh keys for {{ user.name }}"
  authorized_key:
    user: "{{ user.name }}"
    state: present
    key: "{{ lookup('file', '{{ item }}') }}"
  with_fileglob:
    - "files/*.pub"
  become: true
    
- name: add ssh keys for ansible
  authorized_key:
    user: ansible
    state: present
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKG7DNrs2hcOmEG4gXRVyvAgrvoiE2iIBSFoPtRYPHl9 ansible"
  become: true
  
  
# Ensure .config directory exists for regular user
- name: Ensure .config directory exists for users
  become: true
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    force: true
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: '0755'
  loop:
    - { path: "/home/{{ host_user }}/.config", owner: "{{ host_user }}", group: "{{ host_user }}" }
    - { path: "/root/.config", owner: "root", group: "root" }

# - name: Copy Bash files
#   ansible.builtin.copy:
#     src: "{{ item }}"
#     dest: /home/abayoumy/
#     owner: abayoumy
#     group: abayoumy
#     mode: '0755'
#     force: yes
#   with_fileglob:
#     - "files/bash/.bash*"

