---
- name: Register Current User
  ansible.builtin.set_fact:
    host_user: "{{ lookup('ansible.builtin.env', 'USER') }}"
     # "{{ ansible_env['USER']}}"
  become: false

- name: get user
  ansible.builtin.debug:
    msg: "'{{ lookup('ansible.builtin.env', 'USER') }}' is current user"
