- name: check nvim exist
  stat:
    path: /usr/local/bin/nvim
  register: nvim

- name: "Neovim | {{ ansible_os_family }} | Dependencies"
  ansible.builtin.package:
    name:
      - cmake
      - curl
      - pkg-config
      - libtool
      - unzip
      # - python3-ansible-lint
      - ripgrep
    state: present
  become: true
  when: ansible_os_family != "Archlinux"

- name: "Neovim | Checking for Distribution Config"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_os_family }}.yml"
  register: neovim_distribution_config

- name: "Neovim | Run Tasks: {{ ansible_os_family }}"
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"
  when: neovim_distribution_config.stat.exists


- name: Neovim | {{ ansible_os_family }} | Install Neovim
  unarchive:
    src: https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.tar.gz
    dest: /usr/local
    remote_src: yes
    mode: '0755'
    owner: root
    group: root
    extra_opts: [--strip-components=1]
  when: not (nvim.stat.exists) and ansible_architecture == "x86_64"  and  ansible_os_family != "Archlinux"
  become: true


- name: "Neovim | Copy nvim"
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config"
    src: "nvim"
    mode: "0644"
