- name: check nvim exist
  stat:
    path: /usr/local/bin/nvim
  register: nvim

- name: "Neovim | {{ os_family }} | Dependencies"
  ansible.builtin.package:
    name:
      - cmake
      - curl
      - pkg-config
      - libtool
      - unzip
      - ansible-lint
      - ripgrep
    state: present
  become: true
  when: not (ansible_facts['os_family'] == "Archlinux")

- name: "Neovim | {{ os_family }} | Install Neovim"
  kewlfft.aur.aur:
    name: neovim-git
    state: present
  when: ansible_facts['os_family'] == "Archlinux"

- name: Neovim | {{ os_family }} | Install Neovim
  unarchive:
    src: https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.tar.gz
    dest: /usr/local
    remote_src: yes
    mode: '0755'
    owner: root
    group: root
    extra_opts: [--strip-components=1]
  when: not (nvim.stat.exists) and ansible_architecture == "x86_64"  and not (ansible_facts['os_family'] == "Archlinux")
  run_once: true
  
- name: "Neovim | Copy init.lua"
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/nvim/init.lua"
    src: "init.lua"
    mode: "0644"

- name: "Neovim | Copy .luarc.json"
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/nvim/.luarc.json"
    src: ".luarc.json"
    mode: "0644"
- name: "Neovim | Copy modules"
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/nvim/lua"
    src: "lua/"
    mode: "0644"